This is the beginning of the project.

In [1]:
'Setting up Imports'
# !pip install ydata-profiling[notebook]
import pandas as pd
from scipy.stats import zscore
from ydata_profiling import ProfileReport
import re

/Library/Python/3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [2]:
CFI = pd.read_csv("./data/Public_CFI_Network_Directory.2025-3-30.csv")
HIP = pd.read_csv("./data/High Impact Professionals - Public Talent Directory-2.csv")

HIP.head()

,Full Name,Open to,Cause Areas,Roles: Interested,Roles: 1+ years of experience,Years of Work Experience,Professional Summary / Experience,LinkedIn/CV Link,How interested are you in moving into a (new) high-impact job?,How interested are you in founding/co-founding a new high-impact project?,...,Languages,Work Location Preference,Willing to Relocate,Willing to Relocate - Context,Current Employment Status,Money Managed,Max Staff Managed,Other Interests,Profile Last Updated,Outdated Candidate
0,Jordon Harris,"Part-time,Freelance","Animal welfare,Climate change,Environment and ...","Administrative,Business Development,Communicat...","Business Development,Communications,Event Orga...",5.0,With a proven track record of driving results ...,https://www.linkedin.com/in/jordonftempletonha...,5 - I’m actively trying to do this,5 - I’m actively trying to do this,...,English,Fully remote,No,NaN,Freelancing,US$2000000,10.0,"Running a EA workplace or professional group,A...",2025-03-29,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
1,Malavika Malaviya,"Full-time,Part-time,Freelance","Animal welfare,Environment and sustainability","Animal Health / Welfare,Arts and Creative,Busi...","Animal Health / Welfare,Arts & Creative,Busine...",13.0,Vegan lifestyle advocate and founder of @malag...,https://www.linkedin.com/in/malavika-malaviya-...,5 - I’m actively trying to do this,5 - I’m actively trying to do this,...,"English,Hindi,Bengali","Fully remote,Partially remote / Hybrid,In-person",Yes,NaN,Working full time,US$1000000,10.0,"Advisor - Advising an effective organization,B...",2025-03-29,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
2,Chandrakiran HJ,"Full-time,Internship","AI strategy and policy,AI technical research",Product Management,Product Management,1.0,"As a driven student at IIIT B, I thrive on ide...",http://linkedin.com/in/chandrakiran-hj-835b65196,5 - I’m actively trying to do this,5 - I’m actively trying to do this,...,"English,Hindi","Partially remote / Hybrid,Fully remote,In-person",Yes,NaN,Studying,NaN,NaN,NaN,2025-03-29,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
3,Natalie Darby,"Part-time,Full-time,Volunteering","AI strategy and policy,Cybersecurity,Education...","Administrative,Accounting,Business Development...","Accounting,Administrative,Communications,Educa...",30.0,"Broad range of experience in operations, finan...",https://www.linkedin.com/in/natalie-darby/,5 - I’m actively trying to do this,3 - Not actively looking but would consider a ...,...,English,Partially remote / Hybrid,Maybe,I'd work for a time overseas but my home is Au...,"Volunteering,Working part time",US$1200000,15.0,"Advisor - Advising an effective organization,B...",2025-03-28,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
4,Kaitlin Roberts,"Full-time,Part-time","Animal welfare,Climate change,Civilization Res...","Animal Health / Welfare,Arts and Creative,Camp...","Arts & Creative,Community building,Business De...",10.0,Experienced audio storyteller and communicatio...,https://www.linkedin.com/me?trk=p_mwlite_feed-...,5 - I’m actively trying to do this,3 - Not actively looking but would consider a ...,...,"German,English","Fully remote,Partially remote / Hybrid,In-person",Maybe,I am not willing to move to the US,"Freelancing,Volunteering,Studying,Unemployed /...",NaN,6.0,NaN,2025-03-28,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...

In [3]:
CFI.tail()

,Full Name,City,Country,Current Title,Current Employer,Large Firm Affiliation,LinkedIn,Career Path Interests,Cause Area Interests,Openness to a New Role
351,Tim Schwarz,Belrin,Germany,NaN,NaN,NaN,https://www.linkedin.com/in/tim-schwarz-653962...,"Healthcare/Medicine,Politics,Founding an organ...","Bio risk reduction,Existential risk reduction,...",True
352,Zachary Thomas,Matawan,United States of America,Operations & HR,EACN,NaN,https://www.linkedin.com/in/zacharythomas10/,"Operations,Founding an organisation,Management...","Building effective altruism,Existential risk r...",NaN
353,Zack Cunich,Canberra,Australia,Junior consultant (0-2 years consulting experi...,NaN,PricewaterhouseCoopers,https://www.linkedin.com/in/zack-cunich-9212b5...,"Policy/Government,Research,Grantmaking,Outreac...","Building effective altruism,Existential risk r...",True
354,Zakaria Bahlouli,Dubai,United Arab Emirates,Independent consultant,Self-Employed,Bain,https://www.linkedin.com/in/zakaria-bahlouli/,"Communications/Marketing,Academic research,Gra...",Undecided,True
355,Tan Zhong Chen,Singapore,Singapore,Junior consultant (0-2 years consulting experi...,The Bridgespan Group,NaN,https://www.linkedin.com/in/tanzhongchen/,"Communications/Marketing,Grantmaking,Operation...","Building effective altruism,Improving institut...",NaN

I don't currently know any details about these datasets. I don't want to prematurely drop any important records, especially when I don't know anything about them. The goal here is that eventually, we will merge the datasets together. First, we will clean each dataset separately, before we merge using concatenation. This will ensure better data integrity, and concatenation will keep all unique entries rather than only the overlapping observations.

In [4]:
# data profiling: check column types, summarize missing values, look at unique values of categorical fields to identify inconsistencies, generate descriptive statistics

def data_profiling(df):
    print("**Basic Data Overview**")
    print(df.info())
    print("\n")
    
    print("**Missing Values Summary**")
    missings = df.isnull().sum()
    print(missings[missings > 0])
    print("\n")
    
    print("**Unique Values in Categorical Columns**")
    categories = df.select_dtypes(include=['object']).columns
    for col in categories:
        unique_values = df[col].unique()
        print(f"{col}: {len(unique_values)} unique values")
        print(f"Sample values: {unique_values[:10]}")
    print("\n")
    
    print("**Descriptive Statistics for Numeric Columns**")
    print(df.describe())

In [5]:
data_profiling(CFI)

**Basic Data Overview**
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 356 entries, 0 to 355
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Full Name               356 non-null    object
 1   City                    354 non-null    object
 2   Country                 355 non-null    object
 3   Current Title           327 non-null    object
 4   Current Employer        222 non-null    object
 5   Large Firm Affiliation  141 non-null    object
 6   LinkedIn                353 non-null    object
 7   Career Path Interests   312 non-null    object
 8   Cause Area Interests    264 non-null    object
 9   Openness to a New Role  243 non-null    object
dtypes: object(10)
memory usage: 27.9+ KB
None


**Missing Values Summary**
City                        2
Country                     1
Current Title              29
Current Employer          134
Large Firm Affiliation    215
LinkedIn                    3
Career Path Interests      44
Cause Area Interests       92
Openness to a New Role    113
dtype: int64


**Unique Values in Categorical Columns**
Full Name: 355 unique values
Sample values: ['Abdullah  Al Qayyim' 'Aditi Sharma' 'Andrew  Dornon' 'Anurag Dey'
 'Barth Cabouat' 'Carlo  Cristobal' 'Carolin  Oelschläger'
 'Celine  Delacharlerie' 'Clara  Ruiz Linaje' 'David Aguirre']
City: 182 unique values
Sample values: ['New Brunswick' 'Bangalore' 'Austin' 'Stockholm' 'Nairobi'
 'Washington DC' 'Hamburg' 'Singapore' 'Montreal' 'Sydney']
Country: 55 unique values
Sample values: ['Canada' 'India' 'United States of America' 'Sweden' 'Kenya' 'Germany'
 'Singapore' 'Australia' 'United Kingdom' 'Netherlands']
Current Title: 11 unique values
Sample values: ['Independent consultant' 'Consultant (2-4 years experience)' 'Other'
 'Junior consultant (0-2 years consulting experience)'
 'Managing Director and Partner' 'Project leader (4-6 years experience)'
 'Student' nan 'Founder' 'Partner']
Current Employer: 194 unique values
Sample values: ['Abdullahandbeyond, MCAF' 'VMware' 'TaskHuman' 'Analysys Mason'
 'One Acre Fund' nan 'Kumi health gmbH' 'Scalable Impact' 'EIDU'
 'Blue Horizon']
Large Firm Affiliation: 13 unique values
Sample values: [nan 'Boston Consulting Group' 'Deloitte' 'Accenture' 'Ernst & Young'
 'McKinsey' 'None (e.g. student)' 'Bain' 'KPMG' 'PricewaterhouseCoopers']
LinkedIn: 353 unique values
Sample values: ['https://www.linkedin.com/in/abdullahandbeyond/'
 'https://www.linkedin.com/in/aditishm/'
 'https://www.linkedin.com/in/andrewdornon/'
 'https://www.linkedin.com/in/anuragdey/'
 'https://www.linkedin.com/in/barthcabouat/'
 'https://www.linkedin.com/in/carlocristobal/' nan
 'https://www.linkedin.com/in/celinedelacharlerie/'
 'https://www.linkedin.com/in/clararuizlinaje/'
 'https://www.linkedin.com/in/mdaguirre/']
Career Path Interests: 298 unique values
Sample values: [nan 'Academic research,Healthcare/Medicine,Operations'
 'Technology,Operations,Communications/Marketing'
 'Technology,Product management' 'Product management,Technology'
 'Outreach & Community Building'
 'Technology,Data science/Data visualization,Operations'
 'Operations,Finance/Accounting' 'Academic research,Technology'
 'Politics,Policy/Government']
Cause Area Interests: 260 unique values
Sample values: [nan
 'Animal welfare,Environment and sustainability,Climate change,Poverty and health ( low-income and middle-income countries)'
 'Climate change,Environment and sustainability,Scientific/technological progress and economic growth'
 'Longtermism,Climate change,Environment and sustainability,Scientific/technological progress and economic growth,Space governance'
 'Scientific/technological progress and economic growth,Bio risk reduction,Risks posed by artificial intelligence (technical),Risks posed by artificial intelligence (policy)'
 'Improving institutional decision making'
 'Risks posed by artificial intelligence (technical),Risks posed by artificial intelligence (policy)'
 'Building effective altruism'
 'Risks posed by artificial intelligence (technical),Risks posed by artificial intelligence (policy),Mental health'
 'Global priorities research,Poverty and health (high-income areas),Building effective altruism,Risks posed by artificial intelligence (policy),Education and employment,Environment and sustainability']
Openness to a New Role: 2 unique values
Sample values: [nan True]


**Descriptive Statistics for Numeric Columns**
                 Full Name    City                   Country  \
count                  356     354                       355
unique                 355     181                        54
top     Haindavi  Kandarpa  London  United States of America
freq                     2      44                       109

                            Current Title    Current Employer  \
count                                 327                 222
unique                                 10                 193
top     Consultant (2-4 years experience)  McKinsey & Company
freq                                   64                   5

         Large Firm Affiliation                                  LinkedIn  \
count                       141                                       353
unique                       12                                       352
top     Boston Consulting Group  https://www.linkedin.com/in/nwheeler443/
freq                         32                                         2

       Career Path Interests  \
count                    312
unique                   297
top               Management
freq                       4

                                     Cause Area Interests  \
count                                                 264
unique                                                259
top     Climate change,Environment and sustainability,...
freq                                                    2

       Openness to a New Role
count                     243
unique                      1
top                      True
freq                      243

In [6]:
data_profiling(HIP)

**Basic Data Overview**
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2374 entries, 0 to 2373
Data columns (total 26 columns):
 #   Column                                                                     Non-Null Count  Dtype
---  ------                                                                     --------------  -----
 0   Full Name                                                                  2374 non-null   object
 1   Open to                                                                    2369 non-null   object
 2   Cause Areas                                                                2374 non-null   object
 3   Roles: Interested                                                          2373 non-null   object
 4   Roles: 1+ years of experience                                              2360 non-null   object
 5   Years of Work Experience                                                   2368 non-null   float64
 6   Professional Summary / Experience                                          2246 non-null   object
 7   LinkedIn/CV Link                                                           2370 non-null   object
 8   How interested are you in moving into a (new) high-impact job?             2374 non-null   object
 9   How interested are you in founding/co-founding a new high-impact project?  1919 non-null   object
 10  New Project - Needs                                                        1308 non-null   object
 11  Time spent engaging with Effective Altruism (EA)                           2370 non-null   object
 12  Available From                                                             2369 non-null   object
 13  Country                                                                    2372 non-null   object
 14  City                                                                       2255 non-null   object
 15  Timezone                                                                   2359 non-null   object
 16  Languages                                                                  2368 non-null   object
 17  Work Location Preference                                                   2372 non-null   object
 18  Willing to Relocate                                                        2371 non-null   object
 19  Willing to Relocate - Context                                              1578 non-null   object
 20  Current Employment Status                                                  2373 non-null   object
 21  Money Managed                                                              1569 non-null   object
 22  Max Staff Managed                                                          1930 non-null   float64
 23  Other Interests                                                            1983 non-null   object
 24  Profile Last Updated                                                       2374 non-null   object
 25  Outdated Candidate                                                         2374 non-null   object
dtypes: float64(2), object(24)
memory usage: 482.3+ KB
None


**Missing Values Summary**
Open to                                                                         5
Roles: Interested                                                               1
Roles: 1+ years of experience                                                  14
Years of Work Experience                                                        6
Professional Summary / Experience                                             128
LinkedIn/CV Link                                                                4
How interested are you in founding/co-founding a new high-impact project?     455
New Project - Needs                                                          1066
Time spent engaging with Effective Altruism (EA)                                4
Available From                                                                  5
Country                                                                         2
City                                                                          119
Timezone                                                                       15
Languages                                                                       6
Work Location Preference                                                        2
Willing to Relocate                                                             3
Willing to Relocate - Context                                                 796
Current Employment Status                                                       1
Money Managed                                                                 805
Max Staff Managed                                                             444
Other Interests                                                               391
dtype: int64


**Unique Values in Categorical Columns**
Full Name: 2359 unique values
Sample values: ['Jordon Harris' 'Malavika Malaviya' 'Chandrakiran HJ' 'Natalie Darby'
 'Kaitlin Roberts' 'Manasa  Ram Raj' 'Jason  Pinelo' 'Marita Calderón'
 "Brenton O'Hara" 'Jamila Musa']
Open to: 130 unique values
Sample values: ['Part-time,Freelance' 'Full-time,Part-time,Freelance'
 'Full-time,Internship' 'Part-time,Full-time,Volunteering'
 'Full-time,Part-time' 'Full-time,Freelance' 'Full-time'
 'Internship,Volunteering' 'Full-time,Part-time,Freelance,Volunteering'
 'Full-time,Part-time,Internship,Volunteering']
Cause Areas: 2047 unique values
Sample values: ['Animal welfare,Climate change,Environment and sustainability,Global health and development,Wild animal welfare,Mental health,Human rights'
 'Animal welfare,Environment and sustainability'
 'AI strategy and policy,AI technical research'
 'AI strategy and policy,Cybersecurity,Education and employment,Economic inequality,Effective giving,Environment and sustainability,Technological / economic growth,Refugees and immigration,Peace / stability / great power relations,Mental health,Improving institutional decision making,Human rights,Global priorities research,Global health and development,EA meta,EA movement building/growth'
 'Animal welfare,Climate change,Civilization Resilience,Economic inequality,Environment and sustainability,Human rights,Wild animal welfare'
 'Equality (e.g. gender / racial / LGBTQ+ / etc),Epistemic institutions,Environment and sustainability,Education and employment,Economic inequality,Climate change,Civilization Resilience,Existential risk reduction,Global priorities research,Human rights,Peace / stability / great power relations'
 'AI strategy and policy,AI technical research,Authoritarianism and corruption,Civilization Resilience,Education and employment,Improving institutional decision making,Risks posed by artificial intelligence,Technological / economic growth'
 'Animal welfare,Climate change,EA movement building/growth,Wild animal welfare,Environment and sustainability'
 'AI technical research,EA meta,EA movement building/growth,Earning to give,Effective giving,Education and employment,Equality (e.g. gender / racial / LGBTQ+ / etc),Existential risk reduction,Risks posed by artificial intelligence,Technological / economic growth,Animal welfare,Wild animal welfare,Environment and sustainability,Economic inequality,Global priorities research,Improving institutional decision making,Mental health,Human rights,Global health and development,AI strategy and policy,Space governance,Refugees and immigration,Epistemic institutions,Climate change,Civilization Resilience,Biosecurity and pandemic preparedness'
 'Global health and development']
Roles: Interested: 2330 unique values
Sample values: ['Administrative,Business Development,Communications,Community building,Marketing,Personal Assistant / Executive Assistant,Social Media,Project Management,Human Resources & People Ops,Customer Success,Corporate Engagement'
 'Animal Health / Welfare,Arts and Creative,Business Development,Campaigns,Communications,Community building,Consulting,Corporate Engagement,Education,Entrepreneurship,Event Organizing,Fundraising,Grantmaking,Leadership and Management,Marketing,Outreach,Public Relations / PR,Research,Social Media,Strategy'
 'Product Management'
 'Administrative,Accounting,Business Development,Campaigns,Communications,Consulting,Corporate Engagement,Customer Success,Data science,Design,Education,Finance,Forecasting,Fundraising,Government,Grantmaking,Human Resources & People Ops,Leadership and Management,Operations,Project Management,Program Management,Quality Assurance,Research,R&D,Strategy'
 'Animal Health / Welfare,Arts and Creative,Campaigns,Communications,Education,Entrepreneurship,Strategy,Research,Project Management,Marketing'
 'Administrative,Campaigns,Communications,Community building,Consulting,Corporate Engagement,Data science,Education,Fundraising,Leadership and Management,Legal,Policy,Program Management,Research,Strategy'
 'Customer Success,Consulting,Human Resources & People Ops,Leadership and Management,Scientist,Software development / Tech,Science,Strategy'
 'Campaigns,Communications,Community building,Policy,Strategy,Research,Project Management,Education,Consulting'
 'Administrative,Consulting,Event Organizing,Entrepreneurship,Human Resources & People Ops,Leadership and Management,Operations,Program Management,Project Management,Grantmaking,Finance'
 'Medical & Health,Operations,Personal Assistant / Executive Assistant,Program Management,Research']
Roles: 1+ years of experience: 2117 unique values
Sample values: ['Business Development,Communications,Event Organizing,Marketing,Project Management,Sales,Strategy'
 'Animal Health / Welfare,Arts & Creative,Business Development,Communications,Community building,Campaigns,Corporate Engagement,Entrepreneurship,Marketing,Policy,Research,Social Media,Strategy'
 'Product Management'
 'Accounting,Administrative,Communications,Education,Finance,Human Resources & People Ops,Leadership and Management,Research,Quality Assurance,Program Management,Project Management,Operations,Medical & Health'
 'Arts & Creative,Community building,Business Development,Entrepreneurship,Product Management,Project Management'
 'Administrative,Campaigns,Communications,Community building,Corporate Engagement,Design,Event Organizing,Leadership and Management,Legal,Operations,Outreach,Policy,Program Management,Project Management,Research,Social Media,Strategy'
 'Engineering,IT,Software development / Tech'
 'Campaigns,Communications,Grantmaking,Research,Strategy,Social Media,Outreach,Event Organizing,Community building,Arts & Creative'
 'Consulting,Event Organizing,Human Resources & People Ops,Operations,Leadership and Management,Project Management,Program Management'
 'Medical & Health,Program Management,Research']
Professional Summary / Experience: 2247 unique values
Sample values: ['With a proven track record of driving results across marketing, sales, and operations, I bring precision, cross-functional collaboration, and a data-driven mindset to elevate your team’s efficiency and impact. My diverse experience, from scaling live event attendance to resolving high-stakes student emergencies as a college leader, equips me to adapt swiftly, solve complex challenges, and deliver measurable success in fast-paced environments.'
 'Vegan lifestyle advocate and founder of @malagoesgreen (16K followers), driving awareness through content, brand collaborations, and community engagement. Previously spent 10+ years in finance and policy at PwC, Michael Page, and Airtel. MBA from Cass Business School, University of London.'
 'As a driven student at IIIT B, I thrive on ideation, creation, and innovative problem-solving. Deeply rooted in the product management space, I’m now channeling my passion toward the transformative potential of AI agentic technologies—bridging technical innovation with real-world impact.'
 'Broad range of experience in operations, finance, learning and development, health and change management. I love working with people, systems and process to improve efficiency.'
 'Experienced audio storyteller and communications strategist with a background at The New York Times and Gimlet Media, where I led projects on environmental issues and human-animal relationships. Passionate about using storytelling to drive empathy and action for animal rights.'
 'Gender equity researcher and advocate with 7+ years leading community programs to eradicate violence against women and girls. Designed 5+ digital literacy initiatives to bridge the gender digital divide; spearheaded research-based advocacy on caste/gender-based violence; analyzed national/international gender case laws to shape policy frameworks. Partnered with NGOs, legal experts, and grassroots collectives to drive systemic change.'
 'Data and AI Engineer, currently training my management skills organizing and assigning activities to EA UPY members in order to accomplish EA UPY Goals in record time'
 'Dedicated communications for social change specialist focused on research and policies. Experience supporting campaigns, research and advocacy for human rights and climate justice (Amnesty International Americas).  Passionate about transdisciplinary collaboration. Intersectional activist for animals. '
 'Operations professional with 10+ years working for nonprofit organizations of all sizes in the US'
 'Pharmacist and public health professional with experience in health program management, research, and policy analysis. ']
LinkedIn/CV Link: 2353 unique values
Sample values: ['https://www.linkedin.com/in/jordonftempletonharris/'
 'https://www.linkedin.com/in/malavika-malaviya-b2600317/'
 'http://linkedin.com/in/chandrakiran-hj-835b65196'
 'https://www.linkedin.com/in/natalie-darby/'
 'https://www.linkedin.com/me?trk=p_mwlite_feed-secondary_nav'
 'https://www.linkedin.com/in/manasaramraj/'
 'https://www.linkedin.com/in/jason-pinelo-14a6a81a5/'
 'https://www.linkedin.com/in/maritacalderon/?locale=en_US '
 'https://www.linkedin.com/in/brentonrohara/'
 'www.linkedin.com/in/jamila-m-013284ab']
How interested are you in moving into a (new) high-impact job?: 5 unique values
Sample values: ['5 - I’m actively trying to do this'
 '1 - I’m not interested in changing roles right now'
 '3 - Not actively looking but would consider a role' '4' '2']
How interested are you in founding/co-founding a new high-impact project?: 6 unique values
Sample values: ['5 - I’m actively trying to do this'
 '3 - Not actively looking but would consider a role' '4'
 '1 - I’m not interested in changing roles right now' '2' nan]
New Project - Needs: 40 unique values
Sample values: [nan 'Collaborators' 'Collaborators,Funding,Project Idea'
 'Funding,Collaborators' 'Other' 'Collaborators,Project Idea,Funding'
 'Collaborators,Funding' 'Funding' 'Project Idea'
 'Collaborators,Funding,Project Idea,Other']
Time spent engaging with Effective Altruism (EA): 6 unique values
Sample values: ['5h - 20h' '20h -100h' '100h+' '<5h'
 'Never heard of "Effective Altruism"/"EA"' nan]
Available From: 477 unique values
Sample values: ['April 16, 2025' 'March 29, 2025' 'April 1, 2025' 'April 7, 2025'
 'June 1, 2025' 'March 27, 2025' 'May 1, 2025' 'March 29, 2027'
 'June 15, 2025' 'September 1, 2025']
Country: 176 unique values
Sample values: ['United States of America' 'India' 'Australia' 'Germany' 'Mexico'
 'Nigeria' 'Canada' 'United Kingdom' 'France' 'Czechia (Czech Republic)']
City: 1112 unique values
Sample values: ['Pittsburgh' 'New Delhi' 'Mysuru' 'Sydney' 'Berlin' 'Hubli' 'Merida'
 'Freiburg im Breisgau' 'Vancouver, WA' nan]
Timezone: 63 unique values
Sample values: ['UTC-05:00 Eastern Time (US and Canada)' 'UTC+05:00  Islamabad - Karachi'
 'UTC-11:00 Coordinated Universal Time-11' 'UTC+11:00 Sydney - Melbourne'
 'UTC+01:00 Amsterdam - Berlin - Bern - Rome - Stockholm - Vienna'
 'UTC+06:00 Dhaka' 'UTC-06:00 Central Time (US and Canada)'
 'UTC-08:00 Pacific Time (US and Canada)'
 'UTC±00:00 Dublin - Edinburgh - Lisbon - London'
 'UTC-12:00 International Date Line West']
Languages: 409 unique values
Sample values: ['English' 'English,Hindi,Bengali' 'English,Hindi' 'German,English'
 'English,Hindi,Tamil' 'Spanish,English,Italian' 'English,Spanish'
 'English,Chinese (Mandarin)' 'English,French' 'Spanish,English,French']
Work Location Preference: 15 unique values
Sample values: ['Fully remote' 'Fully remote,Partially remote / Hybrid,In-person'
 'Partially remote / Hybrid,Fully remote,In-person'
 'Partially remote / Hybrid'
 'In-person,Partially remote / Hybrid,Fully remote'
 'Fully remote,Partially remote / Hybrid'
 'Partially remote / Hybrid,In-person,Fully remote'
 'Partially remote / Hybrid,In-person'
 'Partially remote / Hybrid,Fully remote'
 'Fully remote,In-person,Partially remote / Hybrid']
Willing to Relocate: 10 unique values
Sample values: ['No' 'Yes' 'Maybe' 'Yes,Maybe' 'Maybe,No' 'No,Maybe' 'Maybe,No,Yes'
 'Maybe,Yes' 'Yes,No' nan]
Willing to Relocate - Context: 1488 unique values
Sample values: [nan "I'd work for a time overseas but my home is Australia."
 'I am not willing to move to the US'
 'I am willing to relocate to any place with good opportunity. '
 'Willing to move to Bay Area'
 "I'm currently studying a master's degree in Environmental governance, therefore I can only move from Freiburg during weekends or relocate during semester breaks (even 2 months)"
 'I am due to move to the Netherlands in July 2025. '
 'Dependent on role, I would consider any location.'
 'It truly depends on the role and it it makes sense to move my family'
 'My top preference is to work from home with a willingness to travel as needed.  I would consider relocating for a special opportunity.  ']
Current Employment Status: 127 unique values
Sample values: ['Freelancing' 'Working full time' 'Studying'
 'Volunteering,Working part time'
 'Freelancing,Volunteering,Studying,Unemployed / Seeking employment'
 'Unemployed / Seeking employment' 'Freelancing,Volunteering,Studying'
 'Working part time' 'Working full time,Volunteering'
 'Freelancing,Volunteering']
Money Managed: 297 unique values
Sample values: ['US$2000000' 'US$1000000' nan 'US$1200000' 'US$50' 'US$10000'
 'US$3000000' 'US$0' 'US$100000' 'US$700000']
Other Interests: 295 unique values
Sample values: ['Running a EA workplace or professional group,Advisor - Advising an effective organization'
 'Advisor - Advising an effective organization,Board Member - Sitting on the board of an effective organization'
 nan
 'Advisor - Advising an effective organization,Board Member - Sitting on the board of an effective organization,Pro-bono Work - Doing pro-bono work for an effective organization,Running a EA workplace or professional group'
 'Advisor - Advising an effective organization,Pro-bono Work - Doing pro-bono work for an effective organization,Running initiatives (like fundraising campaigns) at my organization'
 'Advisor - Advising an effective organization,Running a EA workplace or professional group'
 'Advisor - Advising an effective organization,Board Member - Sitting on the board of an effective organization,Running initiatives (like fundraising campaigns) at my organization'
 'Board Member - Sitting on the board of an effective organization'
 'Pro-bono Work - Doing pro-bono work for an effective organization'
 'Advisor - Advising an effective organization']
Profile Last Updated: 340 unique values
Sample values: ['2025-03-29' '2025-03-28' '2025-03-27' '2025-03-26' '2025-03-25'
 '2025-03-24' '2025-03-23' '2025-03-22' '2025-03-21' '2025-03-20']
Outdated Candidate: 2374 unique values
Sample values: ['https://airtable.com/shrSvHwSxxAOAPDxO?prefill_Candidate=recM7G6CghuNpl1Ae'
 'https://airtable.com/shrSvHwSxxAOAPDxO?prefill_Candidate=recqW9zfgwV96eN7y'
 'https://airtable.com/shrSvHwSxxAOAPDxO?prefill_Candidate=recYhm3g5zf7DlkVt'
 'https://airtable.com/shrSvHwSxxAOAPDxO?prefill_Candidate=reciQqE8M7u4O1Jmu'
 'https://airtable.com/shrSvHwSxxAOAPDxO?prefill_Candidate=recSFNdgNlZUwKOmy'
 'https://airtable.com/shrSvHwSxxAOAPDxO?prefill_Candidate=recYDqVzsr070VYdI'

Instead of only focusing on manual cleaning, we can also do some data profiling using the package y-data profiling to make a data quality assessment of our datasets before we actually clean them.

In [7]:
CFI_sample = CFI.sample(n=200, random_state=50)
HIP_sample = HIP.sample(frac=0.05, random_state=40)
ydata_quality_report_CFI = ProfileReport(CFI_sample, title='Pre-Cleaning CFI Quality Report')
ydata_quality_report_HIP = ProfileReport(HIP_sample, title='Pre-Cleaning HIP Quality Report', minimal=True)

In [8]:
ydata_quality_report_CFI.to_notebook_iframe()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 10/10 [00:00<00:00, 107.36it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
ydata_quality_report_HIP.to_notebook_iframe()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/26 [00:00<?, ?it/s]
100%|██████████| 26/26 [00:00<00:00, 130.64it/s]A

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [10]:
ydata_quality_report_HIP.to_file("Pre-Cleaning HIP Quality Report.html")

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [11]:
# syntactic and pattern based error detection/repair on multi-value columns

def standardization(df, column_name):
    df[column_name] = df[column_name].astype(str).str.strip()
    df[column_name] = df[column_name].str.replace(r'\s*,\s*', ',', regex=True) #replace whitespace around a comma
    df[column_name] = df[column_name].str.replace(r'\s*/\s*', '/', regex=True) # replace whitespace around a slash
    return df

In [12]:
standardization(CFI, "Cause Area Interests")
standardization(CFI, "Career Path Interests")
standardization(HIP, "Cause Areas")
standardization(HIP, "Open to")
standardization(HIP, "Roles: Interested")
standardization(HIP, "Roles: 1+ years of experience")
standardization(HIP, "New Project - Needs")
standardization(HIP, "Languages")
standardization(HIP, "Work Location Preference")
standardization(HIP, "Current Employment Status")
standardization(HIP, "Other Interests")

,Full Name,Open to,Cause Areas,Roles: Interested,Roles: 1+ years of experience,Years of Work Experience,Professional Summary / Experience,LinkedIn/CV Link,How interested are you in moving into a (new) high-impact job?,How interested are you in founding/co-founding a new high-impact project?,...,Languages,Work Location Preference,Willing to Relocate,Willing to Relocate - Context,Current Employment Status,Money Managed,Max Staff Managed,Other Interests,Profile Last Updated,Outdated Candidate
0,Jordon Harris,"Part-time,Freelance","Animal welfare,Climate change,Environment and ...","Administrative,Business Development,Communicat...","Business Development,Communications,Event Orga...",5.0,With a proven track record of driving results ...,https://www.linkedin.com/in/jordonftempletonha...,5 - I’m actively trying to do this,5 - I’m actively trying to do this,...,English,Fully remote,No,NaN,Freelancing,US$2000000,10.0,"Running a EA workplace or professional group,A...",2025-03-29,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
1,Malavika Malaviya,"Full-time,Part-time,Freelance","Animal welfare,Environment and sustainability","Animal Health/Welfare,Arts and Creative,Busine...","Animal Health/Welfare,Arts & Creative,Business...",13.0,Vegan lifestyle advocate and founder of @malag...,https://www.linkedin.com/in/malavika-malaviya-...,5 - I’m actively trying to do this,5 - I’m actively trying to do this,...,"English,Hindi,Bengali","Fully remote,Partially remote/Hybrid,In-person",Yes,NaN,Working full time,US$1000000,10.0,"Advisor - Advising an effective organization,B...",2025-03-29,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
2,Chandrakiran HJ,"Full-time,Internship","AI strategy and policy,AI technical research",Product Management,Product Management,1.0,"As a driven student at IIIT B, I thrive on ide...",http://linkedin.com/in/chandrakiran-hj-835b65196,5 - I’m actively trying to do this,5 - I’m actively trying to do this,...,"English,Hindi","Partially remote/Hybrid,Fully remote,In-person",Yes,NaN,Studying,NaN,NaN,nan,2025-03-29,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
3,Natalie Darby,"Part-time,Full-time,Volunteering","AI strategy and policy,Cybersecurity,Education...","Administrative,Accounting,Business Development...","Accounting,Administrative,Communications,Educa...",30.0,"Broad range of experience in operations, finan...",https://www.linkedin.com/in/natalie-darby/,5 - I’m actively trying to do this,3 - Not actively looking but would consider a ...,...,English,Partially remote/Hybrid,Maybe,I'd work for a time overseas but my home is Au...,"Volunteering,Working part time",US$1200000,15.0,"Advisor - Advising an effective organization,B...",2025-03-28,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
4,Kaitlin Roberts,"Full-time,Part-time","Animal welfare,Climate change,Civilization Res...","Animal Health/Welfare,Arts and Creative,Campai...","Arts & Creative,Community building,Business De...",10.0,Experienced audio storyteller and communicatio...,https://www.linkedin.com/me?trk=p_mwlite_feed-...,5 - I’m actively trying to do this,3 - Not actively looking but would consider a ...,...,"German,English","Fully remote,Partially remote/Hybrid,In-person",Maybe,I am not willing to move to the US,"Freelancing,Volunteering,Studying,Unemployed/S...",NaN,6.0,nan,2025-03-28,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2369,Greg Gianopoulos,"Full-time,Part-time","EA movement building/growth,Education and empl...","Education,Community building","Communications,Community building",9.0,Created Charity Elections program supported by...,https://www.linkedin.com/in/greggianopoulos/,2,1 - I’m not interested in changing roles right...,...,English,Fully remote,No,NaN,"Studying,Working part time",US$110100,7.0,Running a EA workplace or professional group,2025-01-07,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
2370,Richard Annilo,"Full-time,Part-time,Freelance,Internship","AI strategy and policy,AI technical research,A...","Campaigns,Community building,Communications,Da...","Community building,Research,Strategy",3.0,Relentless generalist with startup and communi...,https://www.linkedin.com/in/richardannilo/,4,3 - Not actively looking but would consider a ...,...,"Estonian,English","Fully remote,Partially remote/Hybrid,In-person",Yes,NaN,Freelancing,US$100000,5.0,Board Member - Sitting on the board of an effe...,2025-02-23,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
2371,Jack Malde,"Full-time,Part-time","AI strategy and policy,Animal welfare,EA meta,...","Animal Health/Welfare,Communications,Campaigns...","Operations,Policy,Research",8.0,US Immigration and Workforce Policy (Bipartisa...,https://www.linkedin.com/in/jack-malde/,5 - I’m actively trying to do this,3 - Not actively looking but would consider a ...,...,English,"Fully remote,Partially remote/Hybrid,In-person",Yes,NaN,Working full time,NaN,1.0,Board Member - Sitting on the board of an effe...,2025-01-07,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
2372,Milan Patel,"Full-time,Part-time,Freelance","Animal welfare,Biosecurity and pandemic prepar...","Communications,Community building,Engineering,...","Consulting,Research,Leadership and Management,...",8.0,"Management consultant, product manager, mindse...",https://www.linkedin.com/mwlite/in/milanmpatel,4,3 - Not actively looking but would consider a ...,...,nan,"Fully remote,Partially remote/Hybrid,In-person","Yes,Maybe",Within the UK,Working full time,US$4000000,30.0,"Advisor - Advising an effective organization,O...",2025-01-14,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
2373,Evan Murphy,"Part-time,Freelance,Volunteering","Cybersecurity,Existential risk reduction,Risks...","Data science,Engineering,Research,Software dev...","Research,Engineering,Software development/Tech",14.0,Technical AI governance researcher and advisor...,https://www.linkedin.com/in/evanrmurphy/,3 - Not actively looking but would consider a ...,3 - Not actively looking but would consider a ...,...,"English,Spanish","Fully remote,Partially remote/Hybrid","Maybe,No",NaN,Working part time,NaN,NaN,"Advisor - Advising an effective organization,B...",2025-01-20,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...

In [13]:
HIP['Country'].value_counts()

Country
United States of America           669
United Kingdom                     299
Germany                            121
India                              106
Netherlands                         90
                                  ...
Ireland,United Kingdom,Pakistan      1
United States of America,France      1
Australia,Canada                     1
United Kingdom,Indonesia,Italy       1
Canada,United States of America      1
Name: count, Length: 175, dtype: int64

In [14]:
CFI['Country'].value_counts()

Country
United States of America    109
United Kingdom               67
Germany                      30
Canada                       13
Netherlands                  12
India                        12
Australia                    11
Kenya                         7
Norway                        6
France                        6
Brazil                        5
Austria                       5
Sweden                        5
Czechia (Czech Republic)      4
Poland                        4
Belgium                       4
Spain                         3
Switzerland                   3
United Arab Emirates          3
Singapore                     3
Finland                       2
Philippines                   2
Vietnam                       2
Argentina                     2
Hungary                       2
Peru                          2
Portugal                      2
Israel                        2
South Africa                  2
Georgia                       1
Greece                        1
Central African Republic      1
Tanzania                      1
Colombia                      1
Mexico                        1
Ukraine                       1
Malawi                        1
Malaysia                      1
Morocco                       1
Ireland                       1
Italy                         1
Chile                         1
Turkey                        1
Ethiopia                      1
Egypt                         1
Japan                         1
Myanmar (formerly Burma)      1
Panama                        1
Tunisia                       1
China                         1
Zimbabwe                      1
Saudi Arabia                  1
Pakistan                      1
Cambodia                      1
Name: count, dtype: int64

In [15]:
def punctuation_elimination(df, column_name):
    df[column_name] = df[column_name].str.replace(r'[.,/()\-&"]', '', regex=True)
    df[column_name] = df[column_name].str.title()
    return df

In [16]:
punctuation_elimination(CFI, "City")
punctuation_elimination(CFI, "Country")
punctuation_elimination(HIP, "City")
punctuation_elimination(HIP, "Country")

,Full Name,Open to,Cause Areas,Roles: Interested,Roles: 1+ years of experience,Years of Work Experience,Professional Summary / Experience,LinkedIn/CV Link,How interested are you in moving into a (new) high-impact job?,How interested are you in founding/co-founding a new high-impact project?,...,Languages,Work Location Preference,Willing to Relocate,Willing to Relocate - Context,Current Employment Status,Money Managed,Max Staff Managed,Other Interests,Profile Last Updated,Outdated Candidate
0,Jordon Harris,"Part-time,Freelance","Animal welfare,Climate change,Environment and ...","Administrative,Business Development,Communicat...","Business Development,Communications,Event Orga...",5.0,With a proven track record of driving results ...,https://www.linkedin.com/in/jordonftempletonha...,5 - I’m actively trying to do this,5 - I’m actively trying to do this,...,English,Fully remote,No,NaN,Freelancing,US$2000000,10.0,"Running a EA workplace or professional group,A...",2025-03-29,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
1,Malavika Malaviya,"Full-time,Part-time,Freelance","Animal welfare,Environment and sustainability","Animal Health/Welfare,Arts and Creative,Busine...","Animal Health/Welfare,Arts & Creative,Business...",13.0,Vegan lifestyle advocate and founder of @malag...,https://www.linkedin.com/in/malavika-malaviya-...,5 - I’m actively trying to do this,5 - I’m actively trying to do this,...,"English,Hindi,Bengali","Fully remote,Partially remote/Hybrid,In-person",Yes,NaN,Working full time,US$1000000,10.0,"Advisor - Advising an effective organization,B...",2025-03-29,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
2,Chandrakiran HJ,"Full-time,Internship","AI strategy and policy,AI technical research",Product Management,Product Management,1.0,"As a driven student at IIIT B, I thrive on ide...",http://linkedin.com/in/chandrakiran-hj-835b65196,5 - I’m actively trying to do this,5 - I’m actively trying to do this,...,"English,Hindi","Partially remote/Hybrid,Fully remote,In-person",Yes,NaN,Studying,NaN,NaN,nan,2025-03-29,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
3,Natalie Darby,"Part-time,Full-time,Volunteering","AI strategy and policy,Cybersecurity,Education...","Administrative,Accounting,Business Development...","Accounting,Administrative,Communications,Educa...",30.0,"Broad range of experience in operations, finan...",https://www.linkedin.com/in/natalie-darby/,5 - I’m actively trying to do this,3 - Not actively looking but would consider a ...,...,English,Partially remote/Hybrid,Maybe,I'd work for a time overseas but my home is Au...,"Volunteering,Working part time",US$1200000,15.0,"Advisor - Advising an effective organization,B...",2025-03-28,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
4,Kaitlin Roberts,"Full-time,Part-time","Animal welfare,Climate change,Civilization Res...","Animal Health/Welfare,Arts and Creative,Campai...","Arts & Creative,Community building,Business De...",10.0,Experienced audio storyteller and communicatio...,https://www.linkedin.com/me?trk=p_mwlite_feed-...,5 - I’m actively trying to do this,3 - Not actively looking but would consider a ...,...,"German,English","Fully remote,Partially remote/Hybrid,In-person",Maybe,I am not willing to move to the US,"Freelancing,Volunteering,Studying,Unemployed/S...",NaN,6.0,nan,2025-03-28,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2369,Greg Gianopoulos,"Full-time,Part-time","EA movement building/growth,Education and empl...","Education,Community building","Communications,Community building",9.0,Created Charity Elections program supported by...,https://www.linkedin.com/in/greggianopoulos/,2,1 - I’m not interested in changing roles right...,...,English,Fully remote,No,NaN,"Studying,Working part time",US$110100,7.0,Running a EA workplace or professional group,2025-01-07,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
2370,Richard Annilo,"Full-time,Part-time,Freelance,Internship","AI strategy and policy,AI technical research,A...","Campaigns,Community building,Communications,Da...","Community building,Research,Strategy",3.0,Relentless generalist with startup and communi...,https://www.linkedin.com/in/richardannilo/,4,3 - Not actively looking but would consider a ...,...,"Estonian,English","Fully remote,Partially remote/Hybrid,In-person",Yes,NaN,Freelancing,US$100000,5.0,Board Member - Sitting on the board of an effe...,2025-02-23,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
2371,Jack Malde,"Full-time,Part-time","AI strategy and policy,Animal welfare,EA meta,...","Animal Health/Welfare,Communications,Campaigns...","Operations,Policy,Research",8.0,US Immigration and Workforce Policy (Bipartisa...,https://www.linkedin.com/in/jack-malde/,5 - I’m actively trying to do this,3 - Not actively looking but would consider a ...,...,English,"Fully remote,Partially remote/Hybrid,In-person",Yes,NaN,Working full time,NaN,1.0,Board Member - Sitting on the board of an effe...,2025-01-07,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
2372,Milan Patel,"Full-time,Part-time,Freelance","Animal welfare,Biosecurity and pandemic prepar...","Communications,Community building,Engineering,...","Consulting,Research,Leadership and Management,...",8.0,"Management consultant, product manager, mindse...",https://www.linkedin.com/mwlite/in/milanmpatel,4,3 - Not actively looking but would consider a ...,...,nan,"Fully remote,Partially remote/Hybrid,In-person","Yes,Maybe",Within the UK,Working full time,US$4000000,30.0,"Advisor - Advising an effective organization,O...",2025-01-14,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
2373,Evan Murphy,"Part-time,Freelance,Volunteering","Cybersecurity,Existential risk reduction,Risks...","Data science,Engineering,Research,Software dev...","Research,Engineering,Software development/Tech",14.0,Technical AI governance researcher and advisor...,https://www.linkedin.com/in/evanrmurphy/,3 - Not actively looking but would consider a ...,3 - Not actively looking but would consider a ...,...,"English,Spanish","Fully remote,Partially remote/Hybrid","Maybe,No",NaN,Working part time,NaN,NaN,"Advisor - Advising an effective organization,B...",2025-01-20,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...

I've decided I only want to see people's LinkedIn profiles, not resumes, from the HIP data, due potential invalid URL formats and to make the columns similar.

In [17]:
print(len(HIP))

2374

In [18]:
HIP = HIP[HIP['LinkedIn/CV Link'].str.contains(r'(https://www\.linkedin\.com|www\.linkedin\.com)', na=False)]

/var/folders/vx/f0n6zqf15h9c22pcp057txxw0000gn/T/ipykernel_35151/530919668.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  HIP = HIP[HIP['LinkedIn/CV Link'].str.contains(r'(https://www\.linkedin\.com|www\.linkedin\.com)', na=False)]

In [19]:
print(len(HIP))

1971

In [20]:
#standardizing column names to match CFI from HIP.
HIP = HIP.rename(columns={'Cause Areas': 'Cause Area Interests'})
HIP = HIP.rename(columns={'LinkedIn/CV Link': 'LinkedIn'})
HIP.head()

,Full Name,Open to,Cause Area Interests,Roles: Interested,Roles: 1+ years of experience,Years of Work Experience,Professional Summary / Experience,LinkedIn,How interested are you in moving into a (new) high-impact job?,How interested are you in founding/co-founding a new high-impact project?,...,Languages,Work Location Preference,Willing to Relocate,Willing to Relocate - Context,Current Employment Status,Money Managed,Max Staff Managed,Other Interests,Profile Last Updated,Outdated Candidate
0,Jordon Harris,"Part-time,Freelance","Animal welfare,Climate change,Environment and ...","Administrative,Business Development,Communicat...","Business Development,Communications,Event Orga...",5.0,With a proven track record of driving results ...,https://www.linkedin.com/in/jordonftempletonha...,5 - I’m actively trying to do this,5 - I’m actively trying to do this,...,English,Fully remote,No,NaN,Freelancing,US$2000000,10.0,"Running a EA workplace or professional group,A...",2025-03-29,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
1,Malavika Malaviya,"Full-time,Part-time,Freelance","Animal welfare,Environment and sustainability","Animal Health/Welfare,Arts and Creative,Busine...","Animal Health/Welfare,Arts & Creative,Business...",13.0,Vegan lifestyle advocate and founder of @malag...,https://www.linkedin.com/in/malavika-malaviya-...,5 - I’m actively trying to do this,5 - I’m actively trying to do this,...,"English,Hindi,Bengali","Fully remote,Partially remote/Hybrid,In-person",Yes,NaN,Working full time,US$1000000,10.0,"Advisor - Advising an effective organization,B...",2025-03-29,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
3,Natalie Darby,"Part-time,Full-time,Volunteering","AI strategy and policy,Cybersecurity,Education...","Administrative,Accounting,Business Development...","Accounting,Administrative,Communications,Educa...",30.0,"Broad range of experience in operations, finan...",https://www.linkedin.com/in/natalie-darby/,5 - I’m actively trying to do this,3 - Not actively looking but would consider a ...,...,English,Partially remote/Hybrid,Maybe,I'd work for a time overseas but my home is Au...,"Volunteering,Working part time",US$1200000,15.0,"Advisor - Advising an effective organization,B...",2025-03-28,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
4,Kaitlin Roberts,"Full-time,Part-time","Animal welfare,Climate change,Civilization Res...","Animal Health/Welfare,Arts and Creative,Campai...","Arts & Creative,Community building,Business De...",10.0,Experienced audio storyteller and communicatio...,https://www.linkedin.com/me?trk=p_mwlite_feed-...,5 - I’m actively trying to do this,3 - Not actively looking but would consider a ...,...,"German,English","Fully remote,Partially remote/Hybrid,In-person",Maybe,I am not willing to move to the US,"Freelancing,Volunteering,Studying,Unemployed/S...",NaN,6.0,nan,2025-03-28,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
5,Manasa Ram Raj,"Full-time,Freelance","Equality (e.g. gender/racial/LGBTQ+/etc),Epist...","Administrative,Campaigns,Communications,Commun...","Administrative,Campaigns,Communications,Commun...",7.0,Gender equity researcher and advocate with 7+ ...,https://www.linkedin.com/in/manasaramraj/,5 - I’m actively trying to do this,5 - I’m actively trying to do this,...,"English,Hindi,Tamil","Fully remote,Partially remote/Hybrid,In-person",Yes,I am willing to relocate to any place with goo...,Unemployed/Seeking employment,US$1000000,8.0,"Advisor - Advising an effective organization,P...",2025-03-28,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...

In [21]:
print(len(CFI))
print(len(HIP))

356
1971

In [22]:
#remove exact duplicates within each dataset separately with dr.drop_duplicates
CFI.drop_duplicates(subset=["Full Name", "LinkedIn"], keep='first')
HIP.drop_duplicates(subset=["Full Name", "LinkedIn"], keep="first")

,Full Name,Open to,Cause Area Interests,Roles: Interested,Roles: 1+ years of experience,Years of Work Experience,Professional Summary / Experience,LinkedIn,How interested are you in moving into a (new) high-impact job?,How interested are you in founding/co-founding a new high-impact project?,...,Languages,Work Location Preference,Willing to Relocate,Willing to Relocate - Context,Current Employment Status,Money Managed,Max Staff Managed,Other Interests,Profile Last Updated,Outdated Candidate
0,Jordon Harris,"Part-time,Freelance","Animal welfare,Climate change,Environment and ...","Administrative,Business Development,Communicat...","Business Development,Communications,Event Orga...",5.0,With a proven track record of driving results ...,https://www.linkedin.com/in/jordonftempletonha...,5 - I’m actively trying to do this,5 - I’m actively trying to do this,...,English,Fully remote,No,NaN,Freelancing,US$2000000,10.0,"Running a EA workplace or professional group,A...",2025-03-29,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
1,Malavika Malaviya,"Full-time,Part-time,Freelance","Animal welfare,Environment and sustainability","Animal Health/Welfare,Arts and Creative,Busine...","Animal Health/Welfare,Arts & Creative,Business...",13.0,Vegan lifestyle advocate and founder of @malag...,https://www.linkedin.com/in/malavika-malaviya-...,5 - I’m actively trying to do this,5 - I’m actively trying to do this,...,"English,Hindi,Bengali","Fully remote,Partially remote/Hybrid,In-person",Yes,NaN,Working full time,US$1000000,10.0,"Advisor - Advising an effective organization,B...",2025-03-29,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
3,Natalie Darby,"Part-time,Full-time,Volunteering","AI strategy and policy,Cybersecurity,Education...","Administrative,Accounting,Business Development...","Accounting,Administrative,Communications,Educa...",30.0,"Broad range of experience in operations, finan...",https://www.linkedin.com/in/natalie-darby/,5 - I’m actively trying to do this,3 - Not actively looking but would consider a ...,...,English,Partially remote/Hybrid,Maybe,I'd work for a time overseas but my home is Au...,"Volunteering,Working part time",US$1200000,15.0,"Advisor - Advising an effective organization,B...",2025-03-28,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
4,Kaitlin Roberts,"Full-time,Part-time","Animal welfare,Climate change,Civilization Res...","Animal Health/Welfare,Arts and Creative,Campai...","Arts & Creative,Community building,Business De...",10.0,Experienced audio storyteller and communicatio...,https://www.linkedin.com/me?trk=p_mwlite_feed-...,5 - I’m actively trying to do this,3 - Not actively looking but would consider a ...,...,"German,English","Fully remote,Partially remote/Hybrid,In-person",Maybe,I am not willing to move to the US,"Freelancing,Volunteering,Studying,Unemployed/S...",NaN,6.0,nan,2025-03-28,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
5,Manasa Ram Raj,"Full-time,Freelance","Equality (e.g. gender/racial/LGBTQ+/etc),Epist...","Administrative,Campaigns,Communications,Commun...","Administrative,Campaigns,Communications,Commun...",7.0,Gender equity researcher and advocate with 7+ ...,https://www.linkedin.com/in/manasaramraj/,5 - I’m actively trying to do this,5 - I’m actively trying to do this,...,"English,Hindi,Tamil","Fully remote,Partially remote/Hybrid,In-person",Yes,I am willing to relocate to any place with goo...,Unemployed/Seeking employment,US$1000000,8.0,"Advisor - Advising an effective organization,P...",2025-03-28,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2369,Greg Gianopoulos,"Full-time,Part-time","EA movement building/growth,Education and empl...","Education,Community building","Communications,Community building",9.0,Created Charity Elections program supported by...,https://www.linkedin.com/in/greggianopoulos/,2,1 - I’m not interested in changing roles right...,...,English,Fully remote,No,NaN,"Studying,Working part time",US$110100,7.0,Running a EA workplace or professional group,2025-01-07,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
2370,Richard Annilo,"Full-time,Part-time,Freelance,Internship","AI strategy and policy,AI technical research,A...","Campaigns,Community building,Communications,Da...","Community building,Research,Strategy",3.0,Relentless generalist with startup and communi...,https://www.linkedin.com/in/richardannilo/,4,3 - Not actively looking but would consider a ...,...,"Estonian,English","Fully remote,Partially remote/Hybrid,In-person",Yes,NaN,Freelancing,US$100000,5.0,Board Member - Sitting on the board of an effe...,2025-02-23,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
2371,Jack Malde,"Full-time,Part-time","AI strategy and policy,Animal welfare,EA meta,...","Animal Health/Welfare,Communications,Campaigns...","Operations,Policy,Research",8.0,US Immigration and Workforce Policy (Bipartisa...,https://www.linkedin.com/in/jack-malde/,5 - I’m actively trying to do this,3 - Not actively looking but would consider a ...,...,English,"Fully remote,Partially remote/Hybrid,In-person",Yes,NaN,Working full time,NaN,1.0,Board Member - Sitting on the board of an effe...,2025-01-07,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
2372,Milan Patel,"Full-time,Part-time,Freelance","Animal welfare,Biosecurity and pandemic prepar...","Communications,Community building,Engineering,...","Consulting,Research,Leadership and Management,...",8.0,"Management consultant, product manager, mindse...",https://www.linkedin.com/mwlite/in/milanmpatel,4,3 - Not actively looking but would consider a ...,...,nan,"Fully remote,Partially remote/Hybrid,In-person","Yes,Maybe",Within the UK,Working full time,US$4000000,30.0,"Advisor - Advising an effective organization,O...",2025-01-14,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
2373,Evan Murphy,"Part-time,Freelance,Volunteering","Cybersecurity,Existential risk reduction,Risks...","Data science,Engineering,Research,Software dev...","Research,Engineering,Software development/Tech",14.0,Technical AI governance researcher and advisor...,https://www.linkedin.com/in/evanrmurphy/,3 - Not actively looking but would consider a ...,3 - Not actively looking but would consider a ...,...,"English,Spanish","Fully remote,Partially remote/Hybrid","Maybe,No",NaN,Working part time,NaN,NaN,"Advisor - Advising an effective organization,B...",2025-01-20,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...

In [23]:
print(len(CFI))
print(len(HIP))

356
1971

We can see that neither dataset had their own duplicates - this should come in handy later.

In [24]:
# handle missing values after some of the preprocessing we just did
null_sums = pd.concat([
    HIP.isnull().sum().rename("HIP_Missing"),
    CFI.isnull().sum().rename("CFI_Missing")
], axis=1)

null_sums = null_sums.fillna(0).astype(int) # they wont have the exact same columns, so for readability we put 0's. 
print(null_sums)

                                                    HIP_Missing  CFI_Missing
Full Name                                                     0            0
Open to                                                       0            0
Cause Area Interests                                          0            0
Roles: Interested                                             0            0
Roles: 1+ years of experience                                 0            0
Years of Work Experience                                      4            0
Professional Summary / Experience                           103            0
LinkedIn                                                      0            3
How interested are you in moving into a (new) h...            0            0
How interested are you in founding/co-founding ...          344            0
New Project - Needs                                           0            0
Time spent engaging with Effective Altruism (EA)              4            0
Available From                                                4            0
Country                                                       1            1
City                                                         94            2
Timezone                                                     11            0
Languages                                                     0            0
Work Location Preference                                      0            0
Willing to Relocate                                           3            0
Willing to Relocate - Context                               667            0
Current Employment Status                                     0            0
Money Managed                                               671            0
Max Staff Managed                                           368            0
Other Interests                                               0            0
Profile Last Updated                                          0            0
Outdated Candidate                                            0            0
Current Title                                                 0           29
Current Employer                                              0          134
Large Firm Affiliation                                        0          215
Career Path Interests                                         0            0
Openness to a New Role                                        0          113

What gaps and trends exist in career area interest, skill evolution, and global representation across the 2 nonprofit professional networks focused on impact-driven work, and how does data quality impact these insights?

In [25]:
def missing_handling(df, *column_name, fill_value="Unknown"):
    for col in column_name:
        if col in df.columns:
            df[col] = df[col].fillna(fill_value)
        else:
            print(f"Column '{col}' not found. skipped." )
    return df

In [26]:
CFI = missing_handling(CFI, 
                       "City", "Country", "LinkedIn", "Current Title", "Current Employer", "Large Firm Affiliation", "Openness to a New Role", "Career Path Interests", "Cause Area Interests",
                       fill_value="Unknown")
HIP = missing_handling(HIP, 
                       "Years of Work Experience", "Professional Summary / Experience", "How interested are you in founding/co-founding a new high-impact project?", "Available From", "City", "Country", "Timezone", "Willing to Relocate", "Willing to Relocate - Context", fill_value="Unknown")
HIP = missing_handling(HIP, "Time spent engaging with Effective Altruism (EA)", fill_value="0h")
HIP = missing_handling(HIP, "Money Managed", fill_value="US$0")
HIP = missing_handling(HIP, "Max Staff Managed", fill_value="0.0")

In [27]:
null_sums = pd.concat([
    HIP.isnull().sum().rename("HIP_Missing"),
    CFI.isnull().sum().rename("CFI_Missing")
], axis=1)

null_sums = null_sums.fillna(0).astype(int) 
print(null_sums)

                                                    HIP_Missing  CFI_Missing
Full Name                                                     0            0
Open to                                                       0            0
Cause Area Interests                                          0            0
Roles: Interested                                             0            0
Roles: 1+ years of experience                                 0            0
Years of Work Experience                                      0            0
Professional Summary / Experience                             0            0
LinkedIn                                                      0            0
How interested are you in moving into a (new) h...            0            0
How interested are you in founding/co-founding ...            0            0
New Project - Needs                                           0            0
Time spent engaging with Effective Altruism (EA)              0            0
Available From                                                0            0
Country                                                       0            0
City                                                          0            0
Timezone                                                      0            0
Languages                                                     0            0
Work Location Preference                                      0            0
Willing to Relocate                                           0            0
Willing to Relocate - Context                                 0            0
Current Employment Status                                     0            0
Money Managed                                                 0            0
Max Staff Managed                                             0            0
Other Interests                                               0            0
Profile Last Updated                                          0            0
Outdated Candidate                                            0            0
Current Title                                                 0            0
Current Employer                                              0            0
Large Firm Affiliation                                        0            0
Career Path Interests                                         0            0
Openness to a New Role                                        0            0

In [28]:
HIP.dtypes

Full Name                                                                    object
Open to                                                                      object
Cause Area Interests                                                         object
Roles: Interested                                                            object
Roles: 1+ years of experience                                                object
Years of Work Experience                                                     object
Professional Summary / Experience                                            object
LinkedIn                                                                     object
How interested are you in moving into a (new) high-impact job?               object
How interested are you in founding/co-founding a new high-impact project?    object
New Project - Needs                                                          object
Time spent engaging with Effective Altruism (EA)                             object
Available From                                                               object
Country                                                                      object
City                                                                         object
Timezone                                                                     object
Languages                                                                    object
Work Location Preference                                                     object
Willing to Relocate                                                          object
Willing to Relocate - Context                                                object
Current Employment Status                                                    object
Money Managed                                                                object
Max Staff Managed                                                            object
Other Interests                                                              object
Profile Last Updated                                                         object
Outdated Candidate                                                           object
dtype: object

In [29]:
# need to convert appropriate string columns to numeric, to detect outliers
def numeric_conversions(df):
    if "Time spent engaging with Effective Altruism (EA)" in df.columns:
        df["Time spent engaging with Effective Altruism (EA)"] = df["Time spent engaging with Effective Altruism (EA)"].astype(str).str.replace("h", "", regex=False)
        df["Time spent engaging with Effective Altruism (EA)"] = pd.to_numeric(df["Time spent engaging with Effective Altruism (EA)"], errors='coerce')

    if "Money Managed" in df.columns:
        df["Money Managed"] = df["Money Managed"].astype(str).str.replace("US$", "", regex=False)
        df["Money Managed"] = pd.to_numeric(df["Money Managed"], errors='coerce')
    
    if "Max Staff Managed" in df.columns:
        df['Max Staff Managed'] = df["Max Staff Managed"].astype(str)
        df["Max Staff Managed"] = df["Max Staff Managed"].str.replace(r'[^\d.]', '', regex=True)
        df['Max Staff Managed'] = pd.to_numeric(df['Max Staff Managed'], errors='coerce')
    
    return df

In [30]:
HIP = numeric_conversions(HIP)

In [31]:
# handle outliers
# z scores for unrealistic values & repair the values : Years of Work Experience, Money Managed, Max Staff Managed
def detecting_numeric_outliers(df, columns, threshold=3):
    specific_outliers = []
    for col in columns:
        if col not in df.columns:
            continue
        if not pd.api.types.is_numeric_dtype(df[col]):
            continue
        not_null_vals = df[col].dropna()
        zscores = zscore(not_null_vals)
        outlier_ids = not_null_vals[abs(zscores) > threshold]
    for idx, value in outlier_ids.items():
        specific_outliers.append({
            "Index": idx,
            "Outlier Column": col,
            "Outlier Value": value,
            **{col: value}
        })
    return  pd.DataFrame(specific_outliers)

In [32]:
numeric_columns = ["Time spent engaging with Effective Altruism (EA)", "Money Managed", "Max Staff Managed"]
outliers = detecting_numeric_outliers(HIP, numeric_columns, threshold=3)
print(f"Outliers detected: {len(outliers)}")
display(outliers)

Outliers detected: 4

   Index     Outlier Column  Outlier Value  Max Staff Managed
0     21  Max Staff Managed       480000.0           480000.0
1   1802  Max Staff Managed       670000.0           670000.0
2   1903  Max Staff Managed       200000.0           200000.0
3   1936  Max Staff Managed       300000.0           300000.0

In [33]:
def repair_outliers(df, outliers_detected, replacement_val = "0.0"):
    for _, row in outliers_detected.iterrows():
        index = row["Index"]
        column = row["Outlier Column"]
        if column in df.columns and index in df.index:
            df.at[index, column] = replacement_val
    return df

In [34]:
numeric_columns = ["Time spent engaging with Effective Altruism (EA)", "Money Managed", "Max Staff Managed"]
outliers = detecting_numeric_outliers(HIP, numeric_columns, threshold=3)
HIP = repair_outliers(HIP, outliers, replacement_val="0")

/var/folders/vx/f0n6zqf15h9c22pcp057txxw0000gn/T/ipykernel_35151/1306370454.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.at[index, column] = replacement_val

Merge point.

In [35]:
combined_data = pd.concat([CFI, HIP], axis=0, ignore_index=True, sort=False)
combined_data = combined_data.fillna("Not Available for Both Datasets")

combined_data

,Full Name,City,Country,Current Title,Current Employer,Large Firm Affiliation,LinkedIn,Career Path Interests,Cause Area Interests,Openness to a New Role,...,Languages,Work Location Preference,Willing to Relocate,Willing to Relocate - Context,Current Employment Status,Money Managed,Max Staff Managed,Other Interests,Profile Last Updated,Outdated Candidate
0,Abdullah Al Qayyim,New Brunswick,Canada,Independent consultant,"Abdullahandbeyond, MCAF",Unknown,https://www.linkedin.com/in/abdullahandbeyond/,nan,nan,Unknown,...,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets
1,Aditi Sharma,Bangalore,India,Consultant (2-4 years experience),VMware,Unknown,https://www.linkedin.com/in/aditishm/,nan,nan,Unknown,...,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets
2,Andrew Dornon,Austin,United States Of America,Other,TaskHuman,Unknown,https://www.linkedin.com/in/andrewdornon/,nan,nan,Unknown,...,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets
3,Anurag Dey,Stockholm,Sweden,Consultant (2-4 years experience),Analysys Mason,Unknown,https://www.linkedin.com/in/anuragdey/,nan,nan,Unknown,...,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets
4,Barth Cabouat,Nairobi,Kenya,Other,One Acre Fund,Unknown,https://www.linkedin.com/in/barthcabouat/,nan,nan,Unknown,...,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2322,Greg Gianopoulos,Asheville North Carolina,United States Of America,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets,https://www.linkedin.com/in/greggianopoulos/,Not Available for Both Datasets,"EA movement building/growth,Education and empl...",Not Available for Both Datasets,...,English,Fully remote,No,Unknown,"Studying,Working part time",110100.0,7.0,Running a EA workplace or professional group,2025-01-07,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
2323,Richard Annilo,Tartu,Estonia,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets,https://www.linkedin.com/in/richardannilo/,Not Available for Both Datasets,"AI strategy and policy,AI technical research,A...",Not Available for Both Datasets,...,"Estonian,English","Fully remote,Partially remote/Hybrid,In-person",Yes,Unknown,Freelancing,100000.0,5.0,Board Member - Sitting on the board of an effe...,2025-02-23,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
2324,Jack Malde,Washington Dc,United States Of America,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets,https://www.linkedin.com/in/jack-malde/,Not Available for Both Datasets,"AI strategy and policy,Animal welfare,EA meta,...",Not Available for Both Datasets,...,English,"Fully remote,Partially remote/Hybrid,In-person",Yes,Unknown,Working full time,0.0,1.0,Board Member - Sitting on the board of an effe...,2025-01-07,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
2325,Milan Patel,Leicester,United Kingdom,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets,https://www.linkedin.com/mwlite/in/milanmpatel,Not Available for Both Datasets,"Animal welfare,Biosecurity and pandemic prepar...",Not Available for Both Datasets,...,nan,"Fully remote,Partially remote/Hybrid,In-person","Yes,Maybe",Within the UK,Working full time,4000000.0,30.0,"Advisor - Advising an effective organization,O...",2025-01-14,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
2326,Evan Murphy,Vancouver Bc,Canadaunited States Of America,Not Available for Both Datasets,Not Available for Both Datasets,Not Available for Both Datasets,https://www.linkedin.com/in/evanrmurphy/,Not Available for Both Datasets,"Cybersecurity,Existential risk reduction,Risks...",Not Available for Both Datasets,...,"English,Spanish","Fully remote,Partially remote/Hybrid","Maybe,No",Unknown,Working part time,0.0,0.0,"Advisor - Advising an effective organization,B...",2025-01-20,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...

In [35]:
# identify and handle post merge duplicates

In [36]:
# align and standardize final categorical fields if applicable

In [37]:
# final missing values check

In [38]:
# write new csv. end part 1 notebook.